name: Daily API Automation Suite

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '0 9 * * *' # Runs every day at 9:00 AM

jobs:
  test-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Newman and Reporter
        run: npm install -g newman newman-reporter-htmlextra

      - name: Execute API Tests
        # Note: We use quotes because the filenames have dots and underscores
        run: |
          newman run "Demo_User.postman_collection.json" \
          -e "JSON_Placeholder_Live.postman_environment.json" \
          -r cli,htmlextra \
          --reporter-htmlextra-export results/report.html

      - name: Save HTML Report
        # This step saves the report so you can download it from the GitHub UI
        uses: actions/upload-artifact@v4
        if: always() # This ensures the report is saved even if a test fails
        with:
          name: api-test-report
          path: results/report.html
